# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Kumquats
tagline:          'A home for all of my academic adventures'
description:      'The internet home of one Alan C. Jamieson.'
url:              http://ripark.github.io
baseurl:          /

author:
  name:           'Alan Jamieson'
  url:            https://twitter.com/drripark

paginate:         5

# Custom vars
version:          0.0.0
lastupdate:       'August 3, 2017'
github_username:  'ripark'
twitter_username: 'drripark'

github:
  repo:           https://github.com/ripark

theme: jekyll-theme-slate
